class TestIncomingTransaction:
    cp_data_good = {'TransactionId': 2252922344,
                    'amount': '9.00',
                    'currency': 'RUB',
                    'payment_amount': '9.00',
                    'payment_currency': 'RUB',
                    'operation_type': 'Payment',
                    'invoice_id': 10135284,
                    'account_id': '1281579',
                    'subscription_id': '',
                    'name': '',
                    'email': '',
                    'create_date': '2024-03-13 17:38:13',
                    'ip_address': '37.75.223.76',
                    'ip_country': 'UA',
                    'ip_city': 'Керчь',
                    'ip_region': 'Автономная Республика Крым',
                    'ip_district': 'Керчь',
                    'ip_latitude': '45.3607',
                    'ip_longitude': '36.4706',
                    'cardid': '6561f3e5f74b401b504748bb',
                    'card_first_six': '220002',
                    'card_last_four': '7028',
                    'card_type': 'MIR',
                    'card_exp_date': '07/28',
                    'issuer': 'RNCB',
                    'issuer_bank_country': 'RU',
                    'description': 'Доступ к сервису',
                    'auth_code': '727208',
                    'token': 'tk_38a54368540bcc7390ac9973ce6c0',
                    'test_mode': True,
                    'status': 'Completed',
                    'gateway_name': 'Tinkoff',
                    'data': '{"type":"subscribe"}',
                    'total_fee': '3.00',
                    'card_product': 'CCD',
                    'payment_method': ''}

    cp_data_bad = {'TransactionId': 2099159774,
                   'amount': '1.00',
                   'currency': 'RUB',
                   'payment_amount': '1.00',
                   'payment_currency': 'RUB',
                   'operation_type': 'Payment',
                   'invoice_id': 10135287,
                   'account_id': '1281580',
                   'subscription_id': '',
                   'name': '',
                   'email': '',
                   'create_date': '2024-03-13 17:39:34',
                   'ip_address': '46.159.165.133',
                   'ip_country': 'RU',
                   'ip_city': 'Новороссийск',
                   'ip_region': 'Краснодарский край',
                   'ip_district': 'Новороссийск',
                   'ip_latitude': '44.72439',
                   'ip_longitude': '37.76752',
                   'cardid': '65f1e4d6952b814bdd77aa5f',
                   'card_first_six': '220220',
                   'card_last_four': '4596',
                   'card_type': 'MIR',
                   'card_exp_date': '01/28',
                   'issuer': 'Sberbank',
                   'issuer_bank_country': 'RU',
                   'description': 'Доступ к сервису onsport24.ru',
                   'test_mode': True,
                   'status': 'Declined',
                   'statuscode': '5',
                   'reason': 'RestrictedCard2',
                   'ReasonCode': '5062',
                   'payment_method': '',
                   'data': '{"type":"subscribe"}'}

    ps_data_good = {'Event': 'Payment',
                    'Amount': '1.00',
                    'Currency': 'RUB',
                    'DateTime': '13.03.2024 20.31.52',
                    'IsTest': 0,
                    'Brand': 'NSPK MIR',
                    'Bank': 'TINKOFF BANK',
                    'Country_Code_Alpha2': 'RU',
                    'TransactionId': 'PS00000394172429',
                    'OrderId': '10135040',
                    'Description': 'Доступ к сервису МИР Кето',
                    'CustomFields': 'original_service_id=21017;ScreenHeight=1283;ScreenWidth=592;JavaEnabled=False;'
                                    'TimeZoneOffset=-300;Region=ru-RU;ColorDepth=24;'
                                    'UserAgent=Mozilla/5.0%20%28Linux%3B%20U%3B%20Android%2011%3B%20ru-ru%'
                                    '3B%20Redmi%209%20Build/RP1A.200720.011%29%20AppleWebKit/537.36%20%28KHTML%2C%'
                                    '20like%20Gecko%29%20Version/4.0%20Chrome/112.0.5615.136%20Mobile%20Safari/'
                                    '537.36%20XiaoMi/MiuiBrowser/14.4.0-gn;acceptHeader=text/html;'
                                    'javaScriptEnabled=True;IP=85.140.9.15;ReceiptEmail=staseremenko97%'
                                    '40gmail.com;IsSendReceipt=True',
                    'Service_Id': '21017',
                    'PaymentMethod': 'Card',
                    'CardMasked': '220070******3767',
                    'ExpirationDate': '03/31',
                    'RRN': '407317263093',
                    'CardHolder': 'User Userovich',
                    'RebillId': 'PS00000394172429'}

    ps_data_bad = {'Event': 'Fail',
                   'Amount': '100.00',
                   'Currency': 'RUB',
                   'DateTime': '13.03.2024 20.25.20',
                   'IsTest': 0,
                   'Brand': 'NSPK MIR',
                   'Bank': 'SAVINGS BANK OF THE RUSSIAN FEDERATION (SBERBANK)',
                   'CountryCodeAlpha2': 'RU',
                   'TransactionId': 'PS00000394168244',
                   'OrderId': '10134684',
                   'Description': 'Доступ к сервису pariexpert.ru',
                   'CustomFields': 'service_id_for_recreate=20145;ScreenHeight=800;ScreenWidth=360;JavaEnabled=False;'
                                   'TimeZoneOffset=-180;Region=ru-RU;ColorDepth=24;'
                                   'UserAgent=Mozilla/5.0%20%28Linux%3B%20Android%2011%3B%20RMX3581%29%20AppleWebKit/'
                                   '537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome/108.0.0.0%20Mobile%20Safari/'
                                   '537.36;acceptHeader=text/html;javaScriptEnabled=True;IP=176.59.166.149;'
                                   'IsSendReceipt=False',
                   'Service_Id': '20145',
                   'PaymentMethod': 'Card',
                   'CardMasked': '220220******2073',
                   'ErrorMessage': 'Exceeds withdrawal frequency limit',
                   'ExpirationDate': '09/27',
                   'RRN': '407317017216',
                   'CardHolder': 'User Userovich',
                   'ErrorCode': '7023',
                   'ClientMessage': 'Невозможно провести платеж'}

    pass
